---
- name: Check Hashicorp Vault values
  hosts: all
  vars:
    - key_data: "{{ lookup('hashi_vault', 'secret=secret/data/tower:') }}"

  tasks:
  - name: get info about "Vagrant" inventory
    uri:
      url: https://localhost/api/v2/inventories/2/
      method: GET
      user: admin
      password: "{{ key_data | json_query('data.admin_pw') }}"
      force_basic_auth: True
      validate_certs: False
    register: tower_api_inventory

  - name: print results to stdout
    debug:
      var: tower_api_inventory
